weights: yolov5m.pt
cfg: ''
data: c:\Users\cdetr\Documents\IFT6759_Deep_learning\data/data_split2/data_split2.yaml
hyp: models\yolov5\data\hyps\hyp.scratch-low.yaml
epochs: 1
batch_size: 32
imgsz: 320
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: cuda:0
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 4
project: models\yolov5\runs\train
name: exp
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 5
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: models\yolov5\runs\train\exp
